version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip3 install -U black flake8 --user
      - run: LC_ALL=C.UTF-8 black --check .
      - run: flake8 .
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3
    steps:
      - run: sudo apt-get install -y git-lfs libcgal-dev libeigen3-dev python3-pip clang
      - run: pip3 install -U pytest pytest-cov pybind11 lxml --user
      - checkout
      - run: git lfs pull
      # install
      # Use clang++ for its smaller memory footprint.
      - run: CC="clang++" pip3 install . --user
      # The actual test
      - run: 
          command: pytest
          working_directory: test/

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
